### PR TITLE
view tags

### PR DESCRIPTION
**Pull request by kelseylemmer**
sample tag inserts  in loaddata.sql to check alphabetical

### CODE REVIEW

**Comment by kelseylemmer** [comment]
also made small change to "categories" in doGet:

changed from:
`if resource == 'categories':
            categories= get_all_categories()
            self._set_headers(200)`
to:
`if resource == 'categories':
            response = get_all_categories()
            self._set_headers(200)`

**Review by bhighlander — APPROVED** [review]
:+1:

**Review by CaseyFerebee — COMMENTED** [review]
looks good

**Review by CaseyFerebee — APPROVED** [review]
looks good

**Review by sarahsaturday — APPROVED** [review]
!

**Pull request merged**
